name: CI-CD

on:
  pull_request:
    types:
      - closed

jobs:
  first-ci-cd-attempt:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false

    steps:
      - name: create a comment on the PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for reporting!'
            })